### ISSUE TITLE
ERGM version requirements

### ISSUE THREAD

**Issue by cds-group** [brieuclehmann/multibergm#35]
sessionInfo()
R version 4.2.0 (2022-04-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.6.6

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] it_IT.UTF-8/it_IT.UTF-8/it_IT.UTF-8/C/it_IT.UTF-8/it_IT.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.0 tools_4.2.0   
> library(multibergm)
Errore: package ‘ergm’ 4.2.2 was found, but <= 3.11.0 is required by ‘multibergm’

**Comment by brieuclehmann** [comment]
Hi, thanks for pointing this out! This is a compatibility issue: I haven't yet updated multibergm to be compatible with ergm, version >= 4.0.0. 

I'd recommend using the `renv` package to create an isolated environment: https://rstudio.github.io/renv/

Otherwise, you could uninstall `ergm` and then try installing `multibergm`. This should then (re)install `ergm` version 3.11.0.
